---
- name: Load variable file for current service {{ service }}
  include_vars: "{{ role_path }}/defaults/{{ service }}.yml"

- name: Backup files to remote
  copy:
    src: "{{ file }}"
    dest: "{{ backup_directory }}/backups_{{ backup_time }}/{{ file | regex_replace('^/', '') | regex_replace('/', '_') }}.backup"
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
  become: yes
  loop: "{{ default_files + vars[service + '_files'] }}"
  loop_control:
    loop_var: file
  ignore_errors: true
  when: not backup_to_local
