---
- name: Backup {{ backup.hosts_group }} files
  hosts: "{{ backup.hosts_group }}"
  gather_facts: False

  vars:
    backup_to_local: true
    backup_directory: "/home/reachengine/"

  tasks:
    - name: Get current date and time
      set_fact:
        backup_time: "{{ lookup('pipe', 'date +%Y-%m-%d-%Hh%Mm') }}"
      run_once: true

    - name: Ensure backup directory exists
      file:
        path: "{{ backup_directory }}"
        state: directory
      become: yes
      when: not backup_to_local

    - name: Backup files to local
      fetch:
        src: "{{ item }}"
        dest: "{{ backup_directory }}/{{ inventory_hostname }}/{{ item | basename }}.{{ backup_time }}.bak"
        flat: yes
      become: yes
      loop: "{{ default_files + backup.files }}"
      ignore_errors: yes
      when: backup_to_local

    - name: Backup files to remote
      copy:
        src: "{{ item }}"
        dest: "{{ backup_directory }}/{{ item | basename }}.{{ backup_time }}.bak"
        remote_src: yes
        owner: root
        group: root
        mode: '0644'
      become: yes
      loop: "{{ default_files + backup.files }}"
      ignore_errors: yes
      when: not backup_to_local
